### ISSUE TITLE
Solid is not defined 

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-tutorial-pastebin#1]
When adding a pastebin

Uncaught Reference Error: 

```
Solid is not defined 
app.js:78
onclick @ (index):33
```

**Comment by melvincarvalho** [comment]
Fix likely to be the same as:

https://github.com/solid/solid-inbox/commit/fbc0efe1e1ded27a51254f5ece1e0a3286ce1ef9

**Comment by deiu** [comment]
Fixed in a10db647b46dadb4b8010c5f27c3feab219b71c6
