### ISSUE TITLE
Cant view any bins

### ISSUE THREAD

**Issue by rod-m** [solid/solid-tutorial-pastebin#4]
I can create a bin, when viewing I get an error
url is https://localhost:8443/?view=%2Fdata-bin%2Ff9efaad0-fbee-11e5-912d-a3ae3fa31a41
the bin looks like this:
@prefix terms: http://purl.org/dc/terms/.
@prefix n: http://rdfs.org/sioc/ns#.

   <> terms:title "nex test"; n:content "test agin" .

When the page loads I get this error: TypeError: g.any is not a function
var title = g.any($rdf.sym(url), DCT('title'));

**Comment by dmitrizagidulin** [comment]
Thanks for reporting - we're working on updating the tutorial today, so we'll take a look.

**Comment by dmitrizagidulin** [comment]
@rod-m This should be fixed as of PR #5. 
Do you mind updating to the newest `master`, and trying again?

**Comment by dmitrizagidulin** [comment]
Closing this, feel free to reopen if this is still an issue.
